name: run
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm init -y
      - run: npm install node-fetch@2 cheerio
      - run: node fetch-data.js
      - run: git config user.email a@b.com
      - run: git config user.name bot
      - run: git add data.json
      - run: "git commit -m update || true"
      - run: git push
